# Generated by Django 4.2.21 on 2025-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profilepic',
            field=models.FileField(blank=True, default='default.png', upload_to='profile_pics/'),
        ),
    ]
