# Generated by Django 4.2.21 on 2025-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0002_alter_myuser_email_alter_myuser_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sibling',
            name='age',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profilepic',
            field=models.FileField(blank=True, default='avatar.png', null=True, upload_to='profiles/'),
        ),
    ]
