# Generated by Django 4.2.13 on 2026-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0003_remove_sibling_age_alter_myuser_profilepic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={},
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
    ]
