# Generated by Django 4.2.13 on 2026-07-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryTeller', '0005_imagegallery_category_imagegallery_is_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='downloads',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='photographer',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='views',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery_videos/'),
        ),
    ]
